### ISSUE TITLE
Go code (benchmarks in particular) are not go-gettable.

### ISSUE THREAD

**Issue by dr2chase** [flanglet/kanzi#10]
It would be nice if this
```
go get -d -t -v github.com/flanglet/kanzi/go/src/kanzi/benchmark
```
obtained the Kanzi benchmarks and all their dependencies.
However, this is the result instead:
```
There was an error running 'go get', stderr = github.com/flanglet/kanzi (download)
package kanzi/bitstream: unrecognized import path "kanzi/bitstream" (import path does not begin with hostname)
package kanzi/entropy: unrecognized import path "kanzi/entropy" (import path does not begin with hostname)
package kanzi/function: unrecognized import path "kanzi/function" (import path does not begin with hostname)
package kanzi/io: unrecognized import path "kanzi/io" (import path does not begin with hostname)
package kanzi/transform: unrecognized import path "kanzi/transform" (import path does not begin with hostname)
```
I realize this may not be fixable; it is however an issue, and preventing inclusion of the Kanzi benchmarks into a suite of benchmarks run somewhat more automatically.  (See https://github.com/dr2chase/bent ).

**Comment by flanglet** [comment]
Agreed. There is some work to be done and I have not found the time yet.
Keeping this in mind.

**Comment by flanglet** [comment]
The Go code is now go-gettable. The new repository is https://github.com/flanglet/kanzi-go
