### ISSUE TITLE
Kanzi not available on Maven Central?

### ISSUE THREAD

**Issue by coreagile** [flanglet/kanzi#12]
Hello! I've got a Clojure project that I'd like to integrate Kanzi into. It uses Leiningen to manage dependencies, which requires it to pull from either a Maven repository (for Java projects, Maven Central is the default) or a Clojure one (for Clojure projects, Clojars is the default).

Is there a plan to get artifacts for Kanzi to be deployed into Maven Central?

**Comment by flanglet** [comment]
Hi,

Two points about your email.
First, I am not a maven user (someone mavenized the project) so I do not
have plan to put artifacts in the maven central repo at this time.
Second, I am wondering how you kanzi because the bitstream is not yet
stable. So, with every new release you have to decompress/recompress your
files. Obviously, at some point I want the bitstream to be stable but  it
limits my ability to tinker with the code and improve compression. And that
leads back to maven. Having the code in the centralized repo while the
bitstream is unstable may be an issue.
Overall, I am not opposed to doing it but I need to understand the
needs/potential issues given the current status of the project,

Thanks.

**Comment by coreagile** [comment]
Ahh.. thanks for that! I hadn’t read far enough to understand that the library wasn’t usable in that way.

I’ll hold off for now and work with standard GZip streams.

Appreciate your response!

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by flanglet** [comment]
Hi,
Thanks for reporting the issue. I just pushed a fix that should address the broken tests.
I agree that tests should be added to the Github actions and will update the script in a few days.
With regard to my comment on the bitstream format (in 2018), it is obsolete and Kanzi has been backward compatible for several releases, so it is no longer a concern.
I will see if I can finally add Kanzi to Maven central after the next release (2.3).

**Comment by flanglet** [comment]
Added maven workflow to Github actions.

**Comment by Friendseeker** [comment]
Hello. I would also like to use Kanzi and is blocked by the fact that it is not on maven central. Any update on this issue?

**Comment by Friendseeker** [comment]
> Publishing to maven central is a PITA. I can't verify a registered namespace. No sure how to proceed from there.

Thanks so much for your work!

Here's the instruction from https://central.sonatype.org/publish/requirements/coordinates/#supported-code-hosting-services-for-personal-groupid

> If you want to use a domain linked to a Hosting service we need you to prove ownership of the account by creating a temporary, public repository with the name of the ticket created to register the groupId. E.g. if you want to use io.github.myusername you must create the public repository OSSRH-TICKETNUMBER like this github.com/myusername/OSSRH-TICKETNUMBER.

> The same applies for the other hosting services, E.g. if you want to use io.gitee.myusername you must create the public repository gitee.com/myusername/OSSRH-TICKETNUMBER.

> At the end of the process when your groupId is registered you can simply delete the empty repository. It is only needed during the registration phase.

So I assume we need to create an OSSRH ticket first. If it is already created then we need to create a public repo with the specific format to verify ownership.

**Comment by flanglet** [comment]
Deeply buried in the doc, it says somewhere that logging in to sonatype central with Github already assigns io.github.username ... 
I deployed kanzi 2.3 ... failed. Will try to fix it.

**Comment by flanglet** [comment]
The doc is a maze of outdated hyperlinks. The easiest way to create a namespace is to login to mvn central via Github. So far mvn deploy fails with an authentication error and publishing a bundle directly from the web page fails for reasons I need to understand.

**Comment by flanglet** [comment]
After fighting with wrong or outdated information, self referencing links, incomplete error messages, etc ... for several hours, I finally managed to push a release to maven central. Even though it is called kanzi-2.3.0, it is a snapshot halfway through the development of 2.4.0 but is should not any visible effect (besides some rounding error in compressed size).

**Comment by Friendseeker** [comment]
> After fighting with wrong or outdated information, self referencing links, incomplete error messages, etc ... for several hours, I finally managed to push a release to maven central. Even though it is called kanzi-2.3.0, it is a snapshot halfway through the development of 2.4.0 but is should not any visible effect (beside some rounding error in compressed size).

Thanks so much for your hard work!

Having Kanzi on Maven Central really helps me and a lot others people who wants to use the library via Maven Central.
