### ISSUE TITLE
no main manifest attribute, in kanzi-x.x.x.jar

### ISSUE THREAD

**Issue by huh02** [flanglet/kanzi#19]
Hi, I apologize in advance, I'm not good enough to compile this project myself and I'm not even a programmer, so I always ask my friend to compile. 
With every next version he compiles I get an error when running
**no main manifest attribute, in kanzi-x.x.x.jar.**
My friend says it's because a this line needs to be added in META-INF\MANIFEST.MF
Main-Class: kanzi.app.Kanzi, which must be terminated by enter.
I always have to unzip kanzi-x.x.x.jar, add this line and zip the file back again.
Is it possible to fix this in the source code so I don't have to do this?
The second thing is that my friend said that the latest version 2.1 is reporting as 2.0.0, so version probably is not overridden some in the source code.

**Comment by flanglet** [comment]
Hello, I am not sure how your friend compiles but there is a manifest in the jar generated by maven or ant:
unzip -l target/kanzi-2.1.0.jar | grep MANIFEST
      131  2022-12-26 15:50   META-INF/MANIFEST.MF
java -j target/kanzi-2.1.0.jar fails with mvn and works with the ant generated jar file. It looks like the content of the MANIFEST.MF file is incorrect with mvn. 
I think I have fixed the issue.  If it does not work, you can always generate the jar file by just typing 'ant'.

**Comment by huh02** [comment]
My friend says:
Hello, I noticed you have <archive> tag in maven-compiler-plugin with manifest, but current maven does not recognize this. Proper way how to add main class is to add maven-jar-plugin and specify main class. I am sending pom.xml which generates jar with proper manifest.mf file. You can make a DIFF and see what I changed. (yeah and I compile it with maven installed with "mvn clean package" command)
[pom.zip](https://github.com/flanglet/kanzi/files/10304749/pom.zip)

**Comment by flanglet** [comment]
I already uploaded a fix to GitHub. Did you or your friend try it?
I would rather use the existing manifest file than create a new manifest section in pom.xml.

**Comment by huh02** [comment]
My friend said he tried it and your fix works. So it's ok now, thanks!

**Comment by flanglet** [comment]
Great. Thanks for reporting this issue.
