### ISSUE TITLE
Documentation: LZ4 release version?

### ISSUE THREAD

**Issue by diegomontoya** [flanglet/kanzi#2]
Which LZ4 release is the code based on? Sorry if I missed in the code but I can't seem to find it. 

Is the latest r129?

**Comment by flanglet** [comment]
Hi,

No it is currently base on an old release of LZ4 (> 1 year old). Updating
the LZ4 code is on my to do list. Hopefully in the next few weeks.

**Comment by flanglet** [comment]
I have not updated this issue in a while but the LZ4 has been updated to R131 in July 2015.
