### ISSUE TITLE
Help with an example on image java!

### ISSUE THREAD

**Issue by RenanFucci** [flanglet/kanzi#3]
Hi Kanzi, it seems like your code is very good and useful. However, i'm trying to use it on an image java and i'm having a lot of problems.
Is there an example of how to use it on image from reading to writing ?
I would appreciate a lot, thanks!!! 
;)

**Comment by flanglet** [comment]
What are you trying to do exactly: "trying to use it" ?
Are you trying to compress an image ? If so, it is very easy and I can post some code.

**Comment by RenanFucci** [comment]
Yes, the goal is using it to compress an image to improve the time when processing and after this, uncompress it back.

**Comment by flanglet** [comment]
OK. Something like that (not tested) should work to compress a java image in memory. The code to compress is only the last 4 lines. Add error management and select transform and entropy coder.

           Image image = ImageIO.read(new File("c:\\temp\\lena.jpg"));
           
           if (image == null)
        	System.exit(1);
           
           int w = image.getWidth(null);
           int h = image.getHeight(null);
           int[] data = new int[w*h];
           byte[] buffer = new byte[data.length*4];

           GraphicsDevice gs = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0];
           GraphicsConfiguration gc = gs.getDefaultConfiguration();
           BufferedImage img = gc.createCompatibleImage(w, h, Transparency.OPAQUE);
           img.getGraphics().drawImage(image, 0, 0, null);           
           img.getRaster().getDataElements(0, 0, w, h, data);      
      
           // Now 'data' contains the image pixels as ints
           
           // Assuming ARGB image
           for (int i=0; i<data.length; i++) 
           {
              buffer[i*4]   = (byte) (data[i] >>> 24);
              buffer[i*4+1] = (byte) (data[i] >>> 24);
              buffer[i*4+2] = (byte) (data[i] >>> 24);
              buffer[i*4+3] = (byte) (data[i] >>> 24);
           }
           
           // Compress and save
           FileOutputStream fos = new FileOutputStream("e:\\temp\\lena.jpg.knz");
           CompressedOutputStream cos = new CompressedOutputStream("FPAQ", "BWT", fos);
           cos.write(buffer);
           cos.close();

**Comment by RenanFucci** [comment]
But where are do you apply WaveletTransform forward and reverse ?

**Comment by flanglet** [comment]
You never mentioned that you want to apply the wavelet transform. You said you wanted to compress.

**Comment by RenanFucci** [comment]
I'm sorry, i thought i was a forum for your WaveletTransform lib. Very new at this site.

**Comment by flanglet** [comment]
No problem. You can see examples of code using the Wavelet transform in TestDWT and TestDWT2.
