### ISSUE TITLE
Go BWT transform freezes on some input

### ISSUE THREAD

**Issue by pzo** [flanglet/kanzi#7]
Trying a BWT transform on a block from the abba file (from the gauntlet corpus) freezes.
[abba-2.gz](https://github.com/flanglet/kanzi/files/1052083/abba-2.gz)

./Kanzi -compress -input=abba-2 -transform=bwt -entropy=none -verbose=4 -overwrite -block=32000000

Kanzi 1.0 (C) 2017,  Frederic Langlet                                                                                                                                                                             
Input file name set to 'abba-2'
Output file name set to 'abba-2.knz'
Block size set to 32000000 bytes
Verbosity set to 4
Overwrite set to true
Checksum set to false
Using BWT transform (stage 1)
Using no entropy codec (stage 2)
Using 1 job
Encoding ...                                                                                                                                                                                                      
{ "type":"BEFORE_TRANSFORM", "id":1, "size":3150180, "time":1496668411814}                                                                                                                                        
^C

**Comment by flanglet** [comment]
Notes:
Issue applies to all languages
input file size is 3150180
No issue when block is is smaller than input (EG. -block=3150176 works).

**Comment by flanglet** [comment]
Fixed issue in DivSufSort (all languages) ssMedian3 and ssMedian5 yielding an incorrect median value.
