### ISSUE TITLE
Go BWT Inverse on a particular file generates "index out of range" error

### ISSUE THREAD

**Issue by pzo** [flanglet/kanzi#8]
Kanzi --compress --input=bwt.bin --output=test.kanzi --transform=BWT --entropy=none --block="13000000" --force
Kanzi 1.1 (C) 2017,  Frederic Langlet               
Encoding ...                                        

Encoding:          793 ms                           
Input size:        12078908                         
Output size:       12078929                         
Ratio:             1.000002                         
Throughput (KB/s): 14874   

Kanzi --decompress --input=test.kanzi

Warning: the input file name does not end with the .KNZ extension                                        
Kanzi 1.1 (C) 2017,  Frederic Langlet               
Decoding ...                                        
runtime error: index out of range    

[bwt.bin.gz](https://github.com/flanglet/kanzi/files/1167562/bwt.bin.gz)

**Comment by flanglet** [comment]
Meh ! Another silly regression. Fixed now.
Thanks for the report.
